baseURL = 'https://2darray.com/'
languageCode = 'en-us'
title = '2darray Warm Logs'
theme = 'hugo-ficurinia'

author = "Parijat Mukherjee"
copyright = "Parijat Mukherjee - [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/)."

paginate = 5
summaryLength = 30

[params]
    description = " Unleashing the power of code — where a software developer pushes the boundaries of technology through experiments and ideas."
    author = "Parijat Mukherjee"
    logo = "/logo.svg"
    favicon = "/favicon.png"
    faviconIco = "/favicon.ico"
    appletouch = "/apple-touch-icon.png"
    svgicon = "/logo.svg"
    icon512 = "/android-chrome-512x512.png"
    cactusCommentsSiteName = ""
    cactusCommentsServerName = ""
    cactusCommentsHomeserver = ""

    imageInArticlePreview = true

    enableShareOnFediverse = true

    enableRelatedArticles = true
    relatedArticlesNum = 2
    forceRedirect = true

[markup]
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = false
        tabWidth = 4
        style = "dracula"
    [markup.tableOfContents]
        endLevel = 5
        ordered = false
        startLevel = 1

[menu]
    [[menu.main]]
        identifier = "blogs"
        name = "Blogs"
        url = "/blogs"
        weight = 99
    [[menu.icons]]
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/parijatmukherjee"
        weight = 10
    [[menu.icons]]
        identifier = "mastodon"
        name = "Mastodon"
        url = ""
        weight = 40
