name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Adjust this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.130.0'
          extended: true # Specify the Hugo version to use

      - name: Build the site
        run: hugo

      - name: Deploy to Server via SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          PASS: ${{ secrets.PASS }}
        run: |
          ssh-keyscan -H 2darray.com >> ~/.ssh/known_hosts
          tar -czf /tmp/hugo_site.tar.gz -C public .
          sshpass -p $PASS scp /tmp/hugo_site.tar.gz github@2darray.com:/tmp/
          sshpass -p $PASS ssh github@2darray.com 'bash -s' < ./scripts/deploy.sh
